In [1]:
import torch
import pandas as pd, numpy as np, matplotlib.pyplot as plt, seaborn as sns
print(torch.__version__)

2.1.0+cu121


#1. Tensors

What?
  >multi-dim array of nos

  >another name for a mat that can have any no of dims

Working?
  > inp (text, img, ...) ***-[convert]->*** tensor ***-[NN model]->*** tensor output

##1.1) basics

to create a tensor -> ***torch.tensor()***

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

to convert tensor to int -> ***tensr.item()***

In [ ]:
tensor_to_int = scalar.item()
tensor_to_int

7

In [ ]:
#vector
vec = torch.tensor([7,7,6])
vec

tensor([7, 7, 6])

In [ ]:
vec.ndim
#no of pairs of sq bracs

1

In [ ]:
vec.shape
#no of elems inside sq bracs

torch.Size([3])

In [ ]:
#Mat
Mat = torch.tensor([[7,8,1],
                    [6,11,3]])
Mat

tensor([[ 7,  8,  1],
        [ 6, 11,  3]])

In [ ]:
Mat.ndim

2

In [ ]:
print("[rows, cols] \n")
Mat.shape

[rows, cols] 



torch.Size([2, 3])

In [ ]:
TENSOR = torch.tensor([[[1,2,3,4],
                        [4,5,6,8],
                        [7,8,9,10]
                        ],
                       [[1,2,3,11],
                        [4,5,6,12],
                        [7,8,9,13]
                        ]])
TENSOR

tensor([[[ 1,  2,  3,  4],
         [ 4,  5,  6,  8],
         [ 7,  8,  9, 10]],

        [[ 1,  2,  3, 11],
         [ 4,  5,  6, 12],
         [ 7,  8,  9, 13]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
print("[depth, rows, cols] \n")
TENSOR.shape

[depth, rows, cols] 



torch.Size([2, 3, 4])

In [ ]:
TENSOR[0]

tensor([[ 1,  2,  3,  4],
        [ 4,  5,  6,  8],
        [ 7,  8,  9, 10]])

##1.2) random tensors

why?
  >NNs start with random nos and then adjust them as they better learn the data

In [ ]:
random_tensor = torch.rand(3,3,4)
random_tensor

tensor([[[0.1229, 0.0217, 0.3812, 0.0357],
         [0.3616, 0.3027, 0.6916, 0.6068],
         [0.0208, 0.8519, 0.6051, 0.7931]],

        [[0.9979, 0.2567, 0.8467, 0.1664],
         [0.9787, 0.6532, 0.2638, 0.1185],
         [0.0659, 0.5915, 0.3405, 0.4329]],

        [[0.1186, 0.3491, 0.6918, 0.2514],
         [0.0038, 0.3875, 0.6512, 0.4487],
         [0.8295, 0.8648, 0.2570, 0.7847]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
random_img_size_tensor = torch.rand(size=(224, 224, 3))
random_img_size_tensor.shape, random_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
random_tensor*zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
zeros.dtype

torch.float32

In [ ]:
ones.dtype

torch.float32

##1.3) range

In [ ]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#tensors alike
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##1.4) datatypes

default dtype?
  >float32

why change the default dtype?
  >float16 -> computation speed ⇑ & accuracy ⇓
  
  >float64 -> computation speed ⇓ & accuracy ⇑

3 big errors with Tensors?
  >1) not right datatype

  >2) not right shape

  >3) not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16 = float_32_tensor.type(torch.float16)
float_16.dtype

torch.float16

In [ ]:
float_16 =  float_32_tensor.type(torch.half)
float_16.dtype

torch.float16

In [ ]:
tensr = float_16 * float_32_tensor
tensr.dtype

torch.float32

In [ ]:
torch.device('cuda:0')

device(type='cuda', index=0)

In [ ]:
tensr.device

device(type='cpu')

##1.5) operations

In [ ]:
tensr = torch.tensor([1,2,3])

In [ ]:
#add
print(tensr + 10)

#multiply
print(tensr*10)

#sub
print(tensr-10)

#div
print(tensr/10)

tensor([11, 12, 13])
tensor([10, 20, 30])
tensor([-9, -8, -7])
tensor([0.1000, 0.2000, 0.3000])


In [ ]:
#elem wise mul
tensr * tensr

tensor([1, 4, 9])

In [ ]:
#Mat mul
torch.matmul(tensr, tensr)

CPU times: user 526 µs, sys: 0 ns, total: 526 µs
Wall time: 457 µs


tensor(14)

Why is PyTorch computation 1000x than usual for loop multiplication?

  >uses **vectorization** to perform operations on Tensors which avoids the use of for loops


In [ ]:
random_tensor = torch.rand(200000)

In [ ]:
%%time
val=0
for i in range(len(random_tensor)):
  val += random_tensor[i]*random_tensor[i]
print(val)

tensor(66526.6875)
CPU times: user 1.86 s, sys: 383 µs, total: 1.86 s
Wall time: 1.87 s


In [ ]:
%%time
print(torch.matmul(random_tensor, random_tensor))

tensor(66528.2188)
CPU times: user 4.09 ms, sys: 0 ns, total: 4.09 ms
Wall time: 3.61 ms


In [ ]:
%%time
print(random_tensor @ random_tensor)

tensor(66528.2188)
CPU times: user 3.2 ms, sys: 0 ns, total: 3.2 ms
Wall time: 3.24 ms


In [ ]:
A = torch.rand(3,2)
B = torch.rand(3,2)

In [ ]:
torch.matmul(A,B.T)

tensor([[0.3500, 0.1299, 0.1387],
        [0.8246, 0.1982, 0.6923],
        [0.1909, 0.0641, 0.0985]])

In [ ]:
torch.mm(A, B.T)

tensor([[0.3500, 0.1299, 0.1387],
        [0.8246, 0.1982, 0.6923],
        [0.1909, 0.0641, 0.0985]])

In [ ]:
random_tensor = torch.randint(0, 100, (3,3), dtype=torch.float32)
random_tensor

tensor([[ 5., 65., 91.],
        [ 7., 41., 99.],
        [70., 56., 23.]])

In [ ]:
random_tensor.dtype

torch.float32

In [ ]:
random_tensor.min()

tensor(5.)

In [ ]:
random_tensor.max()

tensor(99.)

In [ ]:
#won't work on int dtype
random_tensor.mean()

tensor(50.7778)

In [ ]:
random_tensor.sum()

tensor(457.)

In [ ]:
random_tensor.argmin

##1.6) shape opers

In [ ]:
x = torch.arange(1.,13.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [ ]:
x_reshaped = x.reshape(2,3,2)
x_reshaped, x_reshaped.shape

(tensor([[[ 1.,  2.],
          [ 3.,  4.],
          [ 5.,  6.]],
 
         [[ 7.,  8.],
          [ 9., 10.],
          [11., 12.]]]),
 torch.Size([2, 3, 2]))

In [ ]:
z = x.view(2,6)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
         [ 7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([2, 6]))

***tensr.view()*** -> shares same memory loc of tensr meaning it is mutable

In [ ]:
z[:,0][0] = 100
z, x

(tensor([[100.,   2.,   3.,   4.,   5.,   6.],
         [  7.,   8.,   9.,  10.,  11.,  12.]]),
 tensor([100.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.]))

In [ ]:
#stack
x = torch.tensor([[1,2,3,4],
                 [5,6,7,8]])
x_stacked = torch.stack([x,x], dim=1)
x_stacked

tensor([[[1, 2, 3, 4],
         [1, 2, 3, 4]],

        [[5, 6, 7, 8],
         [5, 6, 7, 8]]])

In [ ]:
torch.vstack([x,x])

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 2, 3, 4],
        [5, 6, 7, 8]])

In [ ]:
torch.hstack([x,x])

tensor([[1, 2, 3, 4, 1, 2, 3, 4],
        [5, 6, 7, 8, 5, 6, 7, 8]])

***tensr.squeeze()*** -> removes size 1 dim

In [ ]:
x = torch.zeros(2,1,2,1,2)
x, x.shape

(tensor([[[[[0., 0.]],
 
           [[0., 0.]]]],
 
 
 
         [[[[0., 0.]],
 
           [[0., 0.]]]]]),
 torch.Size([2, 1, 2, 1, 2]))

In [ ]:
x_squeeze = x.squeeze()
x_squeeze, x_squeeze.shape

(tensor([[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]),
 torch.Size([2, 2, 2]))

In [ ]:
v = torch.tensor([1,2,3])
v.squeeze().ndim

1

In [ ]:
x.unsqueeze(0).shape

torch.Size([1, 2, 1, 2, 1, 2])

In [ ]:
v.unsqueeze(0).shape

torch.Size([1, 3])

***tensr.permute()*** -> shifts dims
* returns a view (mutable)

In [ ]:
x = torch.rand(224,100,3)
x.shape

torch.Size([224, 100, 3])

In [ ]:
x_permute = x.permute(2,0,1)
x_permute.shape

torch.Size([3, 224, 100])

In [ ]:
x[0,0,0]

tensor(0.8582)

In [ ]:
x_permute[0,0,0] = 343

In [ ]:
x[0,0,0]

tensor(343.)

##1.7) indexing

In [ ]:
x = torch.arange(1, 10).reshape(1,3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0,0,0]

tensor(1)

In [ ]:
x[0,-1,-1]

tensor(9)

In [ ]:
#row indexing
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#column indexing
x[0,:,0]

tensor([1, 4, 7])

tensor([1, 2, 3])

##1.8) handling numpy arr

In [ ]:
#np arr -> tensor
arr = np.arange(1.0, 8.0)
tensr = torch.from_numpy(arr)
arr, tensr

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

tensor points to the same memory loc of the np arr

In [ ]:
tensr.type(torch.float32)

tensor([1., 2., 3., 4., 5., 6., 7.])

In [ ]:
tensr.dtype

torch.float64

In [ ]:
arr = arr + 1
arr, tensr

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#tensor -> np
tensr = torch.ones(7)
np_tensor = tensr.numpy()
tensr, np_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensr += 1
tensr, np_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

In [ ]:
tensr = tensr + 1
tensr, np_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

##1.9) reproducibility

In [ ]:
A = torch.rand(3,4)
B = torch.rand(3,4)

print(A)
print(B)
print(A==B)

tensor([[0.2075, 0.5889, 0.6748, 0.7700],
        [0.1850, 0.3903, 0.1937, 0.7938],
        [0.4151, 0.1795, 0.0398, 0.8992]])
tensor([[0.1870, 0.2831, 0.1666, 0.4793],
        [0.7603, 0.2360, 0.0278, 0.0146],
        [0.5696, 0.1810, 0.3304, 0.7906]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
torch.manual_seed(42)
C = torch.rand(3,3)
torch.manual_seed(42)
D = torch.rand(3,3)

print(C)
print(D)
print(C==D)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])
tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])


#2. GPU

##2.1) getting GPU

In [ ]:
!nvidia-smi

Fri Feb 23 11:59:36 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   37C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

##2.2) checking for GPU access with PyTorch

In [ ]:
#check if pytorch is connected to GPU(device)
torch.cuda.is_available()

True

In [ ]:
#setup GPU agnostic code -> make it usable
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#no of GPUs
torch.cuda.device_count()

1

##2.3) move tensors to GPU

In [ ]:
tensr = torch.tensor([1,2,3])

print(tensr, tensr.device)

tensor([1, 2, 3]) cpu


tensors by default: on cpu

In [ ]:
#move to GPU
tensor_GPU = tensr.to(device)
tensor_GPU

tensor([1, 2, 3], device='cuda:0')

##2.4) move tensors to cpu

In [ ]:
# tensor_GPU.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

np doesn't work with GPU

sol: move tensor to cpu

In [ ]:
tensor_cpu = tensor_GPU.cpu()
tensor_cpu

tensor([1, 2, 3])

In [ ]:
tensor_cpu.numpy()

array([1, 2, 3])

In [ ]:
torch.cuda.get_device_name()

'Tesla T4'

In [ ]:
torch.cuda.get_device_properties(device)

_CudaDeviceProperties(name='Tesla T4', major=7, minor=5, total_memory=15102MB, multi_processor_count=40)

In [ ]:
torch.cuda.memory_reserved()

2097152

In [ ]:
torch.cuda.mem_get_info()

(15725559808, 15835660288)

## 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Create random tensor
a = torch.rand(7,7)
a

tensor([[0.7863, 0.9505, 0.9587, 0.9676, 0.4812, 0.4563, 0.2253],
        [0.9372, 0.7670, 0.3138, 0.4560, 0.8095, 0.2333, 0.9450],
        [0.0580, 0.1722, 0.4174, 0.6378, 0.6543, 0.1588, 0.7187],
        [0.1869, 0.2812, 0.6603, 0.9351, 0.8564, 0.4772, 0.1624],
        [0.6835, 0.1044, 0.3596, 0.0699, 0.3897, 0.3652, 0.9841],
        [0.2737, 0.2378, 0.9649, 0.5859, 0.5012, 0.4862, 0.5489],
        [0.2555, 0.2511, 0.1827, 0.2169, 0.3797, 0.3938, 0.1628]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor
b = torch.rand(1,7)
# Perform matrix multiplication
c = torch.matmul(a,b.T)
c

tensor([[2.3205],
        [1.8516],
        [1.0218],
        [1.5220],
        [1.3034],
        [1.5728],
        [0.8069]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed


# Create two random tensors
torch.manual_seed(0)
a_seed = torch.rand(7,7)
b_seed = torch.rand(1,7)

# Matrix multiply tensors
c_seed = a_seed @ b_seed.T
c_seed, c_seed.shape

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
torch.manual_seed(1234)
# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(device)
# Create two random tensors on GPU
a_GPU = torch.rand(2,3).to(device)
b_GPU = torch.rand(2,3).to(device)

a_GPU, b_GPU

cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [ ]:
# Perform matmul on tensor_A and tensor_B
c_GPU = a_GPU @ b_GPU.T
c_GPU

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [ ]:
# Find max
print(f"max: {torch.max(c_GPU)}")
# Find min
print(f"min: {torch.min(c_GPU)}")

max: 0.5617256760597229
min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [ ]:
# Find arg max
print(f"argmax: {torch.argmax(c_GPU)}")

# Find arg min
print(f"argmin: {torch.argmin(c_GPU)}")

argmax: 3
argmin: 0



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [ ]:
# Set seed
torch.manual_seed(7)


# Create random tensor
random_tensr = torch.rand(1,1,1,10)


# Remove single dimensions
tensr = random_tensr.squeeze()


# Print out tensors and their shapes
random_tensr, random_tensr.shape, tensr, tensr.shape



(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))